name: tekartik_mdl_js
version: 0.4.2
description: Material design lite base resources and wrappers
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/mdl_js.dart
publish_to: none
environment:
  sdk: '>=2.10.0-0 <3.0.0'
dependencies:
  js: any
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart2
    version: '>=0.6.8+1'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
dev_dependencies:
  test: any
  dev_test: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  process_run: '>=0.10.1'
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2