name: 'tekartik_mdl_js'
version: 0.4.0
description: Material design lite base resources and wrappers
author: Alexandre Roux <alex@tekartik.com>
homepage: https://github.com/tekartik/mdl_js.dart
environment:
  sdk: '>=1.24.3 <2.0.0'
dependencies:
  browser: any
  js: any
  tekartik_browser_utils:
    git:
      url: git://github.com/tekartik/browser_utils.dart
      ref: dart1
  chrome_travis:
     git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
  dart_to_js_script_rewriter: any
transformers:
  - dart_to_js_script_rewriter
dev_dependencies:
  test: any
  dev_test: any
