name: 'tekartik_mdl_js'
version: 0.3.0
description: Material design lite base resources and wrappers
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  tekartik_utils:
    git: git://github.com/alextekartik/tekartik_utils.dart
dev_dependencies:
  test: any
