name: 'tekartik_mdl_js'
version: 0.3.2
description: Material design lite base resources and wrappers
author: Alexandre Roux <alex@tekartik.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  js: any
  tekartik_browser_utils:
    git: git://github.com/tekartik/tekartik_browser_utils.dart
dev_dependencies:
  test: any
  dev_test: any
